### ISSUE TITLE
Wrong Column Name

### ISSUE THREAD

**Issue by syamsathyan** [tracebucket/x1-dictionary-api#7]
@Column(name = "EMAIL_TYPE", nullable = false, columnDefinition = "ENUM('BASE', 'OPTIONAL') default 'BASE'")
    @Enumerated(EnumType.STRING)
    private CurrencyType currencyType;

**Comment by ffazil** [comment]
@bvishwajit Can you look in to this?

**Comment by bvishwajit** [comment]
Fixed via 2c1e1ad92264cb42c940683d8578edfe962d53f3

**Comment by ffazil** [comment]
Fixed via 2c1e1ad92264cb42c940683d8578edfe962d53f3
