### ISSUE TITLE
Wrong Database Column Name

### ISSUE THREAD

**Issue by madhavi-gopinath** [tracebucket/x1-dictionary-api#9]
Why is currency type called EMAIL_TYPE in the database table?

Code:
@Column(name = "EMAIL_TYPE", nullable = false, columnDefinition = "ENUM('BASE', 'OPTIONAL') default 'BASE'")
    @Enumerated(EnumType.STRING)
    private CurrencyType currencyType;

From DefaultCurrency.java

**Comment by bvishwajit** [comment]
can you please take an update? earlier the same thing was brought to notice and it was fixed.
